# Generated by Django 5.2.1 on 2025-06-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_suspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='is_primary',
        ),
    ]
