# Generated by Django 5.2.1 on 2025-06-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_suspect_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
