# Generated by Django 5.2.1 on 2025-05-25 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_id_number', message='ID must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_since',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
