# Generated by Django 5.2.1 on 2025-05-26 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_id_number', message='ID must be exactly 16 digits', regex='^[1-9]\\d{15}$')]),
        ),
    ]
