# Generated by Django 5.2.1 on 2025-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usermfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='email_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='method',
            field=models.CharField(choices=[('qrcode', 'Authenticator App (QR Code)'), ('email', 'Email Code')], default='qrcode', max_length=10),
        ),
    ]
