# Generated by Django 5.2.1 on 2025-06-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usermfa_email_code_usermfa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
