# Generated by Django 5.2.1 on 2025-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usermfa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='email_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
